const constants = {
    FONT_IOS: 'ROBOTO-regular',
    FONT_ANDROID: 'Roboto',

    FONT_WEIGHT_BOLD: '900',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_THIN: '100',

    FONT_SIZE_PAGE_TITLE: 20,
    FONT_SIZE_PAGE_DESCRIPTION: 14,
    // FONT_SIZE_PAGE_CONTENT: 16,
    // FONT_SIZE_IMAGE_TITLE: 34,
    // FONT_SIZE_IMAGE_CONTENT: 16,
    // FONT_SIZE_LIST_ITEM_TITLE: 22,
    // FONT_SIZE_LIST_ITEM_CONTENT: 14,
    FONT_SIZE_LINK: 16,
    FONT_SIZE_INPUT: 16,
    FONT_SIZE_PAGE_ERROR: 16,

    COLOR_PRIMARY: '#fff',
    COLOR_SECONDARY: '#000000',
    COLOR_ACCENT: '#ffa500',
    COLOR_BUTTON_RIPPLE: '#ffa500',
    COLOR_SEPARATION: '#eee',
    COLOR_ALERT: '#FF0000',
    COLOR_OK: '#0abf0a',

    MARGIN_BASIC: 12,
    HEIGHT_TOOLBAR: 56
};

export default constants;
